### ISSUE TITLE
Issues with seasons 2 and onwards not being found on anilist even though season 1 works fine

### ISSUE THREAD

**Issue by SnowySailor** [RickDB/PlexAniSync-Custom-Mappings#86]
My plex uses Japanese titles and when a show has more than one season, the first season is picked up without issue but the second (and any others after it) are "not found" on anilist. Here are a few examples, but this happens with every single show with more than 1 season that I've looked at:

![image](https://github.com/RickDB/PlexAniSync-Custom-Mappings/assets/6320753/4fd8ef2c-4009-44ac-bd29-6f28867bf2d2)
![image](https://github.com/RickDB/PlexAniSync-Custom-Mappings/assets/6320753/00a92b6b-c9a3-4af1-a816-6bb3c6eaf4f7)
![image](https://github.com/RickDB/PlexAniSync-Custom-Mappings/assets/6320753/7ae28fac-6fce-422d-9356-e5c92b4129a0)
![image](https://github.com/RickDB/PlexAniSync-Custom-Mappings/assets/6320753/97c4253a-c5f8-44b7-84a6-45cb1f47c56c)

**What seems to fix the problem:**

Manually copying the entry for the English title, but then replacing it with the Japanese title in my own custom-mappings file. Example for fixing Oshi no Ko:
```yml
- title: "[推しの子]"
    guid: plex://show/62a3245d52758f8243740884
    # imdb: https://www.imdb.com/title/tt21030032/
    # tmdb: https://www.themoviedb.org/tv/203737
    # tvdb: https://www.thetvdb.com/dereferrer/series/421069
    seasons:
      - season: 1
        anilist-id: 150672
      - season: 2
        anilist-id: 166531
```

The exact same plex guid and seasons entries are used, but the title is changed to the Japanese one. I've only tested this on a few shows and it seems to work but I haven't checked more than a handful. When I enter the plex guid link into my browser, it opens the correct show, so I know the guid association is still correct even with the JP title in plex.

I am using this url: `https://raw.githubusercontent.com/RickDB/PlexAniSync-Custom-Mappings/main/series-tvdb.en.yaml` and `ghcr.io/rickdb/plexanisync:latest`
